services:
  postgres:
    image: postgres:${POSTGRES_VERSION:-15}-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
      TZ: "UTC"
    volumes:
      - postgres:/var/lib/postgresql/data:rw

  php:
    build:
      target: dev
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    links:
      - postgres
    volumes:
      - ./:/app/

  nginx:
    image: nginx
    depends_on:
      - php
    links:
      - php
    volumes:
      - ./docker-files/templates:/etc/nginx/templates
      - ./public:/app/public
    ports:
      - "8080:80"
    environment:
      TZ: "UTC"
      NGINX_HOST: _
      NGINX_PORT: 80

volumes:
  postgres:
